"""Add ProxySession model for session tracking

Revision ID: 08f11ae71408
Revises: 9617d630d8f5
Create Date: 2025-11-14 20:07:03.515803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08f11ae71408'
down_revision: Union[str, Sequence[str], None] = '9617d630d8f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proxy_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_id', sa.UUID(), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=False),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_activity', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bytes_transferred', sa.BigInteger(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['token_id'], ['access_tokens.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proxy_sessions_is_active'), 'proxy_sessions', ['is_active'], unique=False)
    op.create_index(op.f('ix_proxy_sessions_last_activity'), 'proxy_sessions', ['last_activity'], unique=False)
    op.create_index(op.f('ix_proxy_sessions_token_id'), 'proxy_sessions', ['token_id'], unique=False)
    op.create_index(op.f('ix_proxy_sessions_user_id'), 'proxy_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proxy_sessions_user_id'), table_name='proxy_sessions')
    op.drop_index(op.f('ix_proxy_sessions_token_id'), table_name='proxy_sessions')
    op.drop_index(op.f('ix_proxy_sessions_last_activity'), table_name='proxy_sessions')
    op.drop_index(op.f('ix_proxy_sessions_is_active'), table_name='proxy_sessions')
    op.drop_table('proxy_sessions')
    # ### end Alembic commands ###
