"""add device_id to proxy_session for device conflict detection

Revision ID: 6ae14fae638e
Revises: cc790f045980
Create Date: 2025-11-16 19:23:12.594119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ae14fae638e'
down_revision: Union[str, Sequence[str], None] = 'cc790f045980'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add device_id column with server_default for existing rows
    op.add_column(
        'proxy_sessions',
        sa.Column('device_id', sa.String(length=255), nullable=False, server_default='legacy')
    )

    # Remove server_default so new rows require explicit device_id
    op.alter_column('proxy_sessions', 'device_id', server_default=None)

    # Add index on device_id for fast lookups
    op.create_index(op.f('ix_proxy_sessions_device_id'), 'proxy_sessions', ['device_id'], unique=False)

    # Add composite index for device conflict detection optimization
    op.create_index(
        'ix_proxy_sessions_token_device_active',
        'proxy_sessions',
        ['token_id', 'device_id', 'is_active'],
        unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop composite index
    op.drop_index('ix_proxy_sessions_token_device_active', table_name='proxy_sessions')

    # Drop device_id index
    op.drop_index(op.f('ix_proxy_sessions_device_id'), table_name='proxy_sessions')

    # Drop device_id column
    op.drop_column('proxy_sessions', 'device_id')
    # ### end Alembic commands ###
