"""Add currency_balance and Transaction model

Revision ID: 9617d630d8f5
Revises: f09519d56544
Create Date: 2025-11-13 13:55:23.120596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9617d630d8f5'
down_revision: Union[str, Sequence[str], None] = 'f09519d56544'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Amount in ZNC (+ for deposit/refund, - for purchase)'),
    sa.Column('transaction_type', sa.Enum('DEPOSIT', 'PURCHASE', 'REFUND', name='transactiontype'), nullable=False, comment='Type of transaction'),
    sa.Column('description', sa.String(), nullable=False, comment='Human-readable description'),
    sa.Column('payment_id', sa.String(), nullable=True, comment='External payment gateway ID (YooKassa, Stripe, etc.)'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_transaction_type'), 'transactions', ['transaction_type'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.add_column('users', sa.Column('currency_balance', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False, comment='Balance in ZNC (Zenzefi Credits)'))
    op.create_index(op.f('ix_users_currency_balance'), 'users', ['currency_balance'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_currency_balance'), table_name='users')
    op.drop_column('users', 'currency_balance')
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_type'), table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
