"""Initial migration: User and AccessToken models v2

Revision ID: a0ba87dda5b7
Revises: 5ee1e942f1ec
Create Date: 2025-10-15 12:27:47.158244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0ba87dda5b7'
down_revision: Union[str, Sequence[str], None] = '5ee1e942f1ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
