"""add scope field to access_tokens

Revision ID: f09519d56544
Revises: b3f64e56a42f
Create Date: 2025-11-10 17:25:58.965289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f09519d56544'
down_revision: Union[str, Sequence[str], None] = 'b3f64e56a42f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_tokens', sa.Column('scope', sa.String(), nullable=False, server_default='full', comment="Access scope: 'full' or 'certificates_only'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('access_tokens', 'scope')
    # ### end Alembic commands ###
